name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    if: github.repository == 'hzqst/CGAssistant'

    steps:
    - uses: actions/checkout@v2

    - name: checkout-CGAssistantJS
      uses: actions/checkout@v2 
      with:
        repository: 'hzqst/CGAssistantJS'
        path: 'CGAssistantJS'
        ssh-key: '${{ secrets.CGASSISTANTJS_PK }}'

    - name: merge-CGAssistantJS
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        dir
        cd CGAssistantJS
        xcopy "CGAssistant\build\" "CGAssistantJS\" /y /e
        git add -A
        git config --global user.name "hzqst"
        git config --global user.email "113660872@qq.com"
        git commit -m "Update binaries from commit %GITHUB_SHA% by %GITHUB_ACTOR%"
        git push
      shell: cmd